name: flexible_tree_layout
description: A package that gives you a flexible tree layout class which can be used to create tree layouts with a simple node/child relationship.
version: 0.0.5
homepage: homepage: https://github.com/vento007/flexible_tree_layout
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

 
flutter:

 